/**
 * GENERATED by scripts/build-responsive-images.js — do not edit.
 *
 * Intrinsic size and available variant widths for every ASCII art file.
 */

export interface AsciiImageMeta {
  width: number;
  height: number;
  widths: number[];
}

export const ASCII_IMAGES: Record<string, AsciiImageMeta> = {
  "/ascii/footer-stele.webp": {
    "width": 1920,
    "height": 1080,
    "widths": [
      960,
      1440,
      1920
    ]
  },
  "/ascii/glyphs/doc-glyph-colonnade.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-eye.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-forge.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-hourglass.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-key.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-loop.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-modes.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-scales.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-scroll.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-seal.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-shield.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-stele.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/glyphs/doc-glyph-vault.webp": {
    "width": 512,
    "height": 512,
    "widths": [
      128,
      256,
      512
    ]
  },
  "/ascii/hero-aptos-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-btc-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-cardano-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-evm-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-landing-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-mint-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-sui-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-ton-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-tron-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-wallet-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/hero-xrp-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-audit-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-brand-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-create2-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-faq-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-how-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-lab-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-lookalike-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/page-security-wide.webp": {
    "width": 1536,
    "height": 1024,
    "widths": [
      640,
      960,
      1280,
      1536
    ]
  },
  "/ascii/side-aqueduct-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-aqueduct.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-colosseum-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-colosseum.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-figure-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-figure.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-forum-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-forum.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-landscape-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-landscape.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-temple-plate.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  },
  "/ascii/side-temple.webp": {
    "width": 1024,
    "height": 1536,
    "widths": [
      320,
      512,
      768,
      1024
    ]
  }
};
