/**
 * GENERATED by scripts/build-worker.js — do not edit.
 *
 * SHA-256 of every worker bundle at build time. Compiled into the app so a
 * swapped worker file cannot present its own matching hash.
 */

export const WORKER_INTEGRITY: Record<string, string> = {
  "/vanity-worker.js": "sha256-dd3ba4ae8e811121f9281a39cfb0fb9ee501c8d3237bfcc24164fe515f378537",
  "/eth-worker.js": "sha256-8a2ccfa7e7ab6689d89a984ff1d26ddeab6901626007145099ffd135457ca9be",
  "/btc-worker.js": "sha256-813640f61c27344a6120f546d1f5cb03fe22824e6db7216c377fd5c8342ec7ea",
  "/tron-worker.js": "sha256-030f606770be55634a8a17df0aee5677aa6b09efeca01d4393c2dbf41e3f7025",
  "/aptos-worker.js": "sha256-5cf7b03b3da1a472813452ecf00c74e73f525496b030b3960235137a6b743997",
  "/sui-worker.js": "sha256-9e0abcc1d5be2b748e870784ee7f0c7771a54b19cd8b048db6430a36ac86bd21",
  "/ton-worker.js": "sha256-adf1d8d57155bbc5541916a9773ec14d8680140c798c90ee227fd927c43fa965",
  "/cardano-worker.js": "sha256-0df1ef2971de59eaa86dbb05457f232bfa87e17067f9b957dc8b7b0eced7f27a",
  "/xrp-worker.js": "sha256-adbac01d31b9ad13ec595c3b43cb2d3961e3c69efa60f1b1de6f0da289ee358d",
  "/seed-worker.js": "sha256-b086182f06335db6b3c4967e5859b741c1595598cb63eec1a708062e1c7776a7"
};

export const WORKER_INTEGRITY_BUILT = "2026-07-29T12:58:09.889Z";
