/**
 * GENERATED by scripts/build-worker.js — do not edit.
 *
 * SHA-256 of every worker bundle at build time. Compiled into the app so a
 * swapped worker file cannot present its own matching hash.
 */

export const WORKER_INTEGRITY: Record<string, string> = {
  "/vanity-worker.js": "sha256-979fd6e7cea57200d5e6d3ec1abd617f5952b8dbaf223774d41e59364fd063c1",
  "/eth-worker.js": "sha256-fed09feee88239aeb976f15182c0f17a1f05c83166834e046206cabcc01a4f6a",
  "/btc-worker.js": "sha256-0daf0930be34f35b00a68f441a4b5fb3c78bf0ff2f5507baa13856e28523e430",
  "/tron-worker.js": "sha256-83b084a3420c355eb11d59c001b1bb64873e203cdfc9c4b7a1c991d4e5fb5855",
  "/aptos-worker.js": "sha256-1c0459c4728edcf8855be6deabc3f5e2b1a330517fecb074587957b8229acc53",
  "/sui-worker.js": "sha256-b45de07b13baf858ca790c3e7a56718be3041a527e2dd983b32d323829956115",
  "/ton-worker.js": "sha256-db5f8b35c880f0ff76f17fb47bdb86d549030a753a064892022e570899dfc83b",
  "/cardano-worker.js": "sha256-061b61c489b59cf79ea094522ef09214c77a8b514fbd653823d269b1edb3d85b",
  "/xrp-worker.js": "sha256-dc985a8e1ee37cf6ee862609e78984b2fa154f51199e2b9a8d864016a7ee841b",
  "/seed-worker.js": "sha256-87bc8c46845612458fef01984b7f3b5bfd03e073557b0547e6ba2df887b65918"
};

export const WORKER_INTEGRITY_BUILT = "2026-08-05T08:10:12.899Z";
